title: Web Opac App
email: info@opacapp.net
description: Public libraries on Android
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://opacapp.net" # the base hostname & protocol for your site
exclude:
  - node_modules
  - gulpfile.js
  - less
destination: ../_site/en
twitter_username: opacapp

# Build settings
markdown: kramdown
kramdown:
  toc_levels: 3..6
